name: app_tesis
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_tts: ^4.2.2
  cloud_firestore: ^5.6.8
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cocer.jpg
    - assets/rallar.jpg
    - assets/cayó.jpg
    - assets/savia.jpg
    - assets/FondoLogin.png
    - assets/perfil.png
    - assets/logo.png
    - assets/main.jpg
