// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpkzMvGnqx-5eL_ChMKQJeqlHHO0DCWs',
    appId: '1:473236795392:web:1533bf5f4e43804db328e5',
    messagingSenderId: '473236795392',
    projectId: 'apptesisss',
    authDomain: 'apptesisss.firebaseapp.com',
    storageBucket: 'apptesisss.firebasestorage.app',
    measurementId: 'G-KEYS61Q0E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09m6O1duxEKniZnCpNuZh6rNlCcOfgoA',
    appId: '1:473236795392:android:734beea808b00020b328e5',
    messagingSenderId: '473236795392',
    projectId: 'apptesisss',
    storageBucket: 'apptesisss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADv3HqMbSa_FDUeBwKE65hrWh4uPSeMQM',
    appId: '1:473236795392:ios:3e10400d5be644a0b328e5',
    messagingSenderId: '473236795392',
    projectId: 'apptesisss',
    storageBucket: 'apptesisss.firebasestorage.app',
    iosBundleId: 'com.example.appTese',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADv3HqMbSa_FDUeBwKE65hrWh4uPSeMQM',
    appId: '1:473236795392:ios:3e10400d5be644a0b328e5',
    messagingSenderId: '473236795392',
    projectId: 'apptesisss',
    storageBucket: 'apptesisss.firebasestorage.app',
    iosBundleId: 'com.example.appTese',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpkzMvGnqx-5eL_ChMKQJeqlHHO0DCWs',
    appId: '1:473236795392:web:d5030e7ba3ee1aa3b328e5',
    messagingSenderId: '473236795392',
    projectId: 'apptesisss',
    authDomain: 'apptesisss.firebaseapp.com',
    storageBucket: 'apptesisss.firebasestorage.app',
    measurementId: 'G-6JE607YDRQ',
  );

}